# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='upvotes',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
